server:
  port: 9094

eureka:
  client:
    fetch-registry: true 
    register-with-eureka: true
    service-url:
      defaulZone: http://localhost:8761/eureka/apps      
       
spring:
  application:
    name: auth
  datasource:
    driverClassName: org.postgresql.Driver
    password: root
    url: jdbc:postgresql://localhost:5432/auth
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    config:
      enabled: 
        false

 

    
jwt:
  secret: secret
  
  
  
